### ISSUE TITLE
RTL version

### ISSUE THREAD

**Issue by alidehghan** [tabler/tabler-react#159]
How can I use RTL version? there is no document nor sample.

**Comment by AaronCoplan** [comment]
@alidehghan At the moment their is no RTL version available - however we would welcome your contribution in working on it!

**Comment by jonthomp** [comment]
@alidehghan you can use the existing tabler RTL CSS to largely achieve this, we just don't have a way built in yet.

Because the tabler CSS is not included in our package you can easily add the RTL CSS yourself. I've [created an rtl branch](https://github.com/tabler/tabler-react/tree/rtl) with an [updated create-react-app example](https://github.com/tabler/tabler-react/tree/rtl/example) to demonstrate.

**Comment by jonthomp** [comment]
@alidehghan an update for you - I've just submitted a PR #164 that adds the CSS, including RTL, into the main tabler-react library along with updated docs on importing them into a project

**Comment by alidehghan** [comment]
thank you very much @jonthomp
