### ISSUE TITLE
Add mouseEvent props to all components

### ISSUE THREAD

**Issue by MrJarv1s** [tabler/tabler-react#199]
It would be important to add props for mouseEvent to all components and their render method. This would provide more flexibility to the users or developers when using the components for their scripts employing the mouseEvents.

Could be implemented in #189 as part of the Tooltip implementation which requires these props to be present in order to work properly. This would also allow the Dropdown component to be used on other components if required.

**Comment by jonthomp** [comment]
The same goes for onClick, onChange and onBlur, they're missing from various components too.

I think we will benefit from having some importable top-level flow types to save on repetition too.

**Comment by MrJarv1s** [comment]
I'll get started on this one.

**Comment by jonthomp** [comment]
Oh no sorry I just meant creating something like a new `/src/flow` a folder and putting the repeatedly used types in it so that they can be easily reused or extended in all the components you're adding them too but actually, it might not be that useful. Just go ahead with how you were going to approach it I think.

**Comment by MrJarv1s** [comment]
@jonthomp I see what you mean now! I like the idea of creating a type export for all events. This could be imported by each components as needed. Once this is merged and you like the way it is implemented, maybe we could start thinking about adding more flow types to it.
