### ISSUE TITLE
Dropdowns should be closed after selecting an option by default

### ISSUE THREAD

**Issue by paolostyle** [tabler/tabler-react#296]
As you can see on the non-React version of Tabler https://tabler.github.io/tabler/# the dropdowns are being closed once you select an option by default. This is not the case for tabler-react. If you'd prefer to not change the default behavior (understandable), can you at least provide an easily configurable way to do what I ask for? Thanks.

**Comment by GregoryHamel** [comment]
Thanks for reporting the issue, we strive to replicate the tabler behaviour has much as possible. This will be fixed in an upcoming release.

I’m sure this could be useful if the dropdown is not being use as navigation, more like an option selection. I hadn’t really thought of that before. I’ll definitely look into it.

Thanks

**Comment by AaronCoplan** [comment]
@paolostyle Sorry for taking so long in getting back to you on this.  By dropdowns on tabler-react, do you mean for example the profile dropdown in the upper right?  Are you suggesting that on clicking an item such as *Settings*, the dropdown should close as it does on the tabler page?  Just trying to get a better understanding of what you are looking for.
![screen shot 2018-10-01 at 4 33 02 am](https://user-images.githubusercontent.com/9311453/46278102-32bc3800-c533-11e8-94b5-85d06d194feb.png)

**Comment by paolostyle** [comment]
Yep, exactly.
