### ISSUE TITLE
Tooltip not working

### ISSUE THREAD

**Issue by rolfwessels** [tabler/tabler-react#305]
When looking at https://tabler.github.io/tabler-react/documentation/#tooltipreact

The tooltip is not responding. I'm having the same issues in my code. 

Version
`"tabler-react": "1.15.0"`

**Comment by AaronCoplan** [comment]
Tooltips as a whole seem to be broken... They are also broken on the [Profile page](https://tabler.github.io/tabler-react/profile).  @GregoryHamel  any insight on this?

**Comment by GregoryHamel** [comment]
@AaronCoplan,
The Tooltip component was written by a much less experienced me. Looking at it, there is probably a lot that can be done to improve the way it works. 

For the reason as to why it is not working right now, I'd have to investigate. My guess is that either:
1. The CSS classes are interfering with one-another;
2. Popper implementation was not done correctly when I did it.

I'll have a look tonight and report back.

**Comment by AaronCoplan** [comment]
When I hover over it and have the Chrome "inspect element" tool open, it shows `opaque: 0;` as one of the properties.  So I'm thinking that something is off with the CSS classes interfering.  That would be awesome if you could look into it!  Thanks @GregoryHamel

**Comment by AaronCoplan** [comment]
@GregoryHamel any update on this?

**Comment by GregoryHamel** [comment]
Yep, I had the chance of looking into it the other night. Sorry for the late reply, I’m on vacation on the other side of the globe.

It’s in part due to the CSS and to the logic in the component. A simple fix is to add the “show” class to the tooltip, but the location is messed up for some reason. Maybe something changed in either React or React Popper that caused the issue.

More to follow when I get back in 2 weeks. @jonthomp feel free to have a look if you can. I understand you did the drop downs with React-popper as well.

**Comment by AaronCoplan** [comment]
@GregoryHamel Thanks for the response - sorry to bother you on vacation!  I'll look into the simple fix of adding "show" for now - if you could take a look when you get back that would be awesome!  Thanks 👍

**Comment by GregoryHamel** [comment]
@AaronCoplan certainly! I really want to get back into this project :)

**Comment by GregoryHamel** [comment]
@AaronCoplan Please review PR.

Cheers,
