### ISSUE TITLE
Make Form.Input modifiable 

### ISSUE THREAD

**Issue by MrJarv1s** [tabler/tabler-react#91]
The current `Form.Input` does not allow to edit its value on the webpage.
React `value` prevents modification. `Form.Input` would require an OnChange Handler as a function that would update the state of the component everytime a change is made.

**Comment by jonthomp** [comment]
@MrJarv1s do you mean `FormTextInput` or `Form.Input`? `Form.Input` already has onChange and value props that you can pass in a handler and value so that you can control it from the outside, however, there is a bug if you are also trying to use the `icon` props, this will be resolved in https://github.com/tabler/tabler-react/pull/73/files#diff-958699d8f9fe581c56494bdcc48ec6b3

**Comment by MrJarv1s** [comment]
That is my bad @jonthomp I looked at the Types and not the Props...
